services:
  db:
    image: postgres:17.6
    container_name: reviewer_postgres
    environment:
      POSTGRES_DB: reviewer
      POSTGRES_USER: reviewer
      POSTGRES_PASSWORD: reviewer
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql


volumes:
  postgres_data:
