services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: reviewer
      POSTGRES_USER: reviewer
      POSTGRES_PASSWORD: reviewer
    ports:
      - "5432:5432"

  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database",
        "postgres://reviewer:reviewer@postgres:5432/reviewer?sslmode=disable",
        "up"
      ]

  app:
    build: .
    depends_on:
      - postgres
      - migrate
    ports:
      - "8080:8080"
